### PR TITLE
Restructure mobile client specs

### PR DESCRIPTION
**Pull request by demerino**
* create directories for `android` and `ios`
* includes a GETTING_STARTED.md for each

### CODE REVIEW

**Comment by bluepnume** [comment]
Do we not want different specs for different languages? Won't the code be different for say, Java vs Kotlin?

**Review by sshropshire — APPROVED** [review]
🌊

**Comment by demerino** [comment]
@bluepnume 

I don't think we will have specs for Kotlin v Java. Similarly, we don't include Java or ObjC code snippets in the BT documentation.

I do think we should have a single spec/document dedicated to our language choice and what the repercussions of it are. We mentioned this today in slack (re ObjC v Swift).

**Review by jonathajones — APPROVED** [review]

**Review by mstuart — APPROVED** [review]
lgtm! Saw the build failed though. It seems to be checking for dead links? :)

https://github.com/paypal/paypal-sdk-spec/pull/13/checks?check_run_id=3415777273

**Pull request merged**
