### PR TITLE
chore: parse only typescript code blocks through typescript compiler

### PR DESCRIPTION
**Pull request by crookedneighbor**
The typescript compiler is very slow. I think it makes the most sense to only run code snippets that are actually documented as being written in Typescript through the compiler.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
(note, there are currently 0 typescript code blocks in this repo)

**Comment by bluepnume** [comment]
This works for me, but there are some typescript codeblocks right now, I think they just aren't labelled correctly. Could you also switch them as part of this PR?

**Comment by crookedneighbor** [comment]
:+1: think I found them all

**Review by nbierdeman — APPROVED** [review]
Nice work! Looks good to me. 🚀

**Review by leogedler — APPROVED** [review]
LGTM

**Pull request merged**
