### PR TITLE
Add getting started guide for js sdk

### PR DESCRIPTION
**Pull request by gregjopa**
First draft at the getting started guide for the JS SDK:

Screen Shot 2021-08-30 at 3 29 36 PM

### CODE REVIEW

**Comment by donraman** [comment]
We got this feedback external developer. Are we going to address these? I am jotting them so that others more knowledgeable in JavaScript can think/ponder more.

- This is not great JavaScript:
window.paypal.Buttons().render('#paypal-button-container');
You should call Buttons() with new Buttons(), e.g. new paypal.Buttons(), since it's capitalized.
- If you call window.paypal.Buttons().render('#paypal-button-container') twice for example, it will render the buttons twice. This should check to see if there's an existing instance already created, and if so, then console.error not render it twice.
- It would be great if this issue was handled properly and there was actually a .destroy method that could be called on a new button instance created (see https://github.com/paypal/paypal-checkout-components/issues/1176).
- It embedded some weird hash in my URL bar:
       http://localhost:3000/en/my-account/billing/upgrade?plan=team#zoid-paypal-buttons-4d8bac61ce_mdq6mtu6mja
-  Detect if the developer is using an ad-blocker and if so then don't pollute the console
- In the SDK url loaded, what happens if I want to do both authorize and capture, e.g. render a form that lets me do both subscriptions and also one-time payments? This is very confusing.
- On the screen that says "Don't see the secure PayPal browser? We'll help you re-launch the window to complete your purchase" and then there's a link that says "Click to Continue" (underlined). Ok so on this screen, there's this tiny X at the top right, and I have to click exactly on it, it's not like 40px padding like a real button like every other common modal.

**Comment by donraman** [comment]
We got this feedback external developer. Are we going to address these? I am jotting them so that others more knowledgeable in JavaScript can think/ponder more.

- This is not great JavaScript:
window.paypal.Buttons().render('#paypal-button-container');
You should call Buttons() with new Buttons(), e.g. new paypal.Buttons(), since it's capitalized.
 If you call window.paypal.Buttons().render('#paypal-button-container') twice for example, it will render the buttons twice. 
- This should check to see if there's an existing instance already created, and if so, then console.error not render it twice.
- It would be great if this issue was handled properly and there was actually a .destroy method that could be called on a new button instance created (see Destroy method paypal-checkout-components#1176).
- It embedded some weird hash in my URL bar:
- http://localhost:3000/en/my-account/billing/upgrade?plan=team#zoid-paypal-buttons-4d8bac61ce_mdq6mtu6mja
- Detect if the developer is using an ad-blocker and if so then don't pollute the console
- In the SDK url loaded, what happens if I want to do both authorize and capture, e.g. render a form that lets me do both subscriptions and also one-time payments? This is very confusing.
- On the screen that says "Don't see the secure PayPal browser? We'll help you re-launch the window to complete your purchase" and then there's a link that says "Click to Continue" (underlined). Ok so on this screen, there's this tiny X at the top right, and I have to click exactly on it, it's not like 40px padding like a real button like every other common modal.

**Comment by bluepnume** [comment]
> This is not great JavaScript:
> window.paypal.Buttons().render('#paypal-button-container');
> You should call Buttons() with new Buttons(), e.g. new paypal.Buttons(), since it's capitalized.

It's capitalized to indicate that it is a "base component" that can be instantiated and rendered multiple times. It follows the convention of a React-style component, e.g.

```javascript
function Button() {
    return <button>click me</button>
}
```

-- there is no expectation here that `Button` will be new'd up.

> If you call window.paypal.Buttons().render('#paypal-button-container') twice for example, it will render the buttons twice.
> This should check to see if there's an existing instance already created, and if so, then console.error not render it twice.

No... the expectation is that merchants can render the component multiple times. It's not intended to be a singleton, and it would be weird to enforce that.

> It would be great if this issue was handled properly and there was actually a .destroy method that could be called on a new button instance created (see Destroy method paypal-checkout-components#1176).

I'm not clear on this point. There is a `.destroy()` method

> It embedded some weird hash in my URL bar:
> http://localhost:3000/en/my-account/billing/upgrade?plan=team#zoid-paypal-buttons-4d8bac61ce_mdq6mtu6mja

This is news to me, and sounds like a bug. @gregjopa have you ever seen this before?

> Detect if the developer is using an ad-blocker and if so then don't pollute the console

Ideally the console should only be used for non-errors in debug mode, so agreed on this.

> In the SDK url loaded, what happens if I want to do both authorize and capture, e.g. render a form that lets me do both subscriptions and also one-time payments? This is very confusing.

Agreed this is less ideal right now, and stems from the fact that we need to do up-front eligibility to decide which components and buttons to ship with the SDK.

@gregjopa I have some ideas around this, like what if we allow passing `intent=*` or `intent=capture,authorize` which returns only FIs which are eligible for both?

> On the screen that says "Don't see the secure PayPal browser? We'll help you re-launch the window to complete your purchase" and then there's a link that says "Click to Continue" (underlined). Ok so on this screen, there's this tiny X at the top right, and I have to click exactly on it, it's not like 40px padding like a real button like every other common modal.

This is good feedback and something we should fix.

**Comment by gregjopa** [comment]
> > This is not great JavaScript:
> > window.paypal.Buttons().render('#paypal-button-container');
> > You should call Buttons() with new Buttons(), e.g. new paypal.Buttons(), since it's capitalized.
> 
> It's capitalized to indicate that it is a "base component" that can be instantiated and rendered multiple times. It follows the convention of a React-style component, e.g.
> 
> ```js
> function Button() {
>     return <button>click me</button>
> }
> ```
> 

In addtion, braintree-web and Stripe do not use the `new` operator in their api either. I think `new` and `this` are complex parts of JS and we don't want them as part of our public api. Ex: https://stripe.com/docs/js/initializing
Screen Shot 2021-09-01 at 9 38 46 AM



> -- there is no expectation here that `Button` will be new'd up.
> 
> > If you call window.paypal.Buttons().render('#paypal-button-container') twice for example, it will render the buttons twice.
> > This should check to see if there's an existing instance already created, and if so, then console.error not render it twice.
> 
> No... the expectation is that merchants can render the component multiple times. It's not intended to be a singleton, and it would be weird to enforce that.
> 
> > It would be great if this issue was handled properly and there was actually a .destroy method that could be called on a new button instance created (see Destroy method paypal-checkout-components#1176).
> 
> I'm not clear on this point. There is a `.destroy()` method
> 

Yes we provide `close()` to solve this use case. This allows devs to clean up a component from the DOM:

```js
// initialize the component
const btn1 = window.paypal.Buttons();

// render the component
btn1.render('body');

// remove the component
btn1.close();
```

> > It embedded some weird hash in my URL bar:
> > http://localhost:3000/en/my-account/billing/upgrade?plan=team#zoid-paypal-buttons-4d8bac61ce_mdq6mtu6mja
> 
> This is news to me, and sounds like a bug. @gregjopa have you ever seen this before?
> 

I haven't seen this one before. Happy to dig into it if there's a reproduction available. 

> > In the SDK url loaded, what happens if I want to do both authorize and capture, e.g. render a form that lets me do both subscriptions and also one-time payments? This is very confusing.
> 
> Agreed this is less ideal right now, and stems from the fact that we need to do up-front eligibility to decide which components and buttons to ship with the SDK.
> 
> @gregjopa I have some ideas around this, like what if we allow passing `intent=*` or `intent=capture,authorize` which returns only FIs which are eligible for both?
> 
I like introducing support for multiple intents with `intent=capture,authorize` so no sdk reload is needed when toggling between the two.

For rendering a subscriptions button and orders button on the same page, we recently added support for this with the `data-namespace`/`data-uid` feature. This allows for multiple JS SDKs to live on the same page and each of those SDKs can have different eligibility embedded in them. More details here: https://engineering.paypalcorp.com/confluence/display/Checkout/Supporting+multiple+JS+SDK+scripts+on+the+same+page

> > On the screen that says "Don't see the secure PayPal browser? We'll help you re-launch the window to complete your purchase" and then there's a link that says "Click to Continue" (underlined). Ok so on this screen, there's this tiny X at the top right, and I have to click exactly on it, it's not like 40px padding like a real button like every other common modal.
> 
> This is good feedback and something we should fix.

Agreed. For reference, here's the "X". We could definitely make it more noticeable and accessible. 
Screen Shot 2021-09-01 at 10 06 48 AM

**Comment by westeezy** [comment]
Thanks @gregjopa for starting the document. We used it as the base of the Getting Started work we (@jplukarski  and myself) had done, but as we wanted to modify a few spots we just went ahead and created a new branch for it. 

There are some good conversations going on in here related to feedback we had for the PayPal SDK so let's move those to discussions as necessary.

**Pull request closed without merging**
